[[redirects]]
  from = "/webgl-shader-template/"
  to = "https://nmattia.github.io/webgl-shader-template/"
  status = 200

[[redirects]]
  from = "/webgl-shader-template/*"
  to = "https://nmattia.github.io/webgl-shader-template/:splat"
  status = 200
